### ISSUE TITLE
Allow PHP version to be set via argument

### ISSUE THREAD

**Issue by longwave** [ddev/github-action-setup-ddev#34]
When using this as CI, sometimes you want a matrix of different PHP versions to test against. To do this at the moment you need to disable autostart, set the version, and then manually start, e.g.

```
      - uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      - name: Setup PHP Version
        run: ddev config --php-version ${{ matrix.php }}

      - name: Start ddev
        run: ddev start
```

It would be nicer DX if we could just say
```
      - uses: ddev/github-action-setup-ddev@v1
        with:
          php-version: ${{ matrix.php }}
```

**Comment by alexpott** [comment]
Maybe it should be more flexible something like:
```
      - uses: ddev/github-action-setup-ddev@v1
        with:
          before-start:
            - ddev config --php-version ${{ matrix.php }}
            - ddev config --something-else ${{ matrix.something }}
```

Like PHP is just 1 thing you might want to vary by....

**Comment by donquixote** [comment]
Or could we have a `config:` key for config overrides?
This would have the same structure as the `config.yaml` file.

```yaml
      - uses: ddev/github-action-setup-ddev@v1
        with:
          ddev-config:
            php_version: ${{ matrix.php }}
```

**Comment by donquixote** [comment]
There could be another key for extensions.

```
      - uses: ddev/github-action-setup-ddev@v1
        with:
          ddev-get:
            - ddev/ddev-drupal-contrib
            - ddev/ddev-selenium-standalone-chrome
          ddev-config:
            php_version: ${{ matrix.php }}
```
